// Social Content Hub — weekly data. GENERATED by build/build_data.py. Do not hand-edit.
window.SCH_DATA = {
  "weeks": [
    {
      "label": "31 Aug – 6 Sep 2026",
      "commencing": "2026-08-31",
      "theme": "Ipswich v Liverpool · BOYLE Sports Irish Greyhound Derby SFs · Arc Trials Day - Longchamp",
      "updated": "2026-08-30",
      "priorities": [
        {
          "title": "Ipswich v Liverpool",
          "note": "Super Boost · 25% BBB · Free To Play",
          "level": "high"
        },
        {
          "title": "BOYLE Sports Irish Greyhound Derby SFs",
          "note": "Bet & Get · Money Back · BOG",
          "level": "high"
        },
        {
          "title": "Arc Trials Day - Longchamp",
          "note": "Super Boost · Money Back",
          "level": "high"
        },
        {
          "title": "Top Gaffers Scheme",
          "note": "Bet & Get",
          "level": "high"
        },
        {
          "title": "Rovers v Shelbourne",
          "note": "Super Boost",
          "level": "high"
        }
      ],
      "schedule": []
    }
  ],
  "links": [
    {
      "label": "Air (Imagery)",
      "url": "https://app.air.inc"
    },
    {
      "label": "BoyleSports Sports",
      "url": "https://www.boylesports.com/sports/football"
    },
    {
      "label": "BoyleSports Casino",
      "url": "https://games.boylesports.com"
    },
    {
      "label": "Brandwatch",
      "url": "https://www.brandwatch.com/"
    }
  ],
  "promoWeeks": [
    {
      "label": "31 Aug – 6 Sep 2026",
      "items": [
        {
          "day": "Monday",
          "match": "Aston Villa v Arsenal",
          "competition": "Football",
          "promo": "50% Bet Builder Boost: Aston Villa v Arsenal",
          "type": "50% BBB",
          "twitter": "🚀 Win 50% more with Bet Builder Boost as Aston Villa take on Arsenal.\n\nTap below to view the full market.",
          "facebook": "Win 50% more with Bet Builder Boost as Aston Villa take on Arsenal.\n\n📲 Full market — https://www.boylesports.com/promotions/online/football",
          "air": "https://app.air.inc/a/b66a2bf08/b/09240a6c-f6d9-4b8e-876d-86422a734715",
          "boylesports": "https://www.boylesports.com/promotions/online/football",
          "image": "",
          "note": "Midweek Football; Air design folder"
        },
        {
          "day": "Monday",
          "match": "Barcelona v Rayo Vallecano",
          "competition": "Football",
          "promo": "25% Bet Builder Boost: Barcelona v Rayo Vallecano",
          "type": "25% BBB",
          "twitter": "🚀 Win 25% more with Bet Builder Boost as Barcelona face Rayo Vallecano.\n\nTap below to view the full market.",
          "facebook": "Win 25% more with Bet Builder Boost as Barcelona face Rayo Vallecano.\n\n📲 Full market — https://www.boylesports.com/promotions/online/football",
          "air": "https://app.air.inc/a/b0a12f79e",
          "boylesports": "https://www.boylesports.com/promotions/online/football",
          "image": "",
          "note": "Midweek Football; Air design folder"
        },
        {
          "day": "Monday",
          "match": "Top Gaffers Scheme",
          "competition": "Football",
          "promo": "Top Gaffers Campaign Live",
          "type": "Bet & Get",
          "twitter": "Our Top Gaffers scheme is live this week — get involved and back your picks.\n\nTap below to find out more.",
          "facebook": "Our Top Gaffers scheme is live this week — get involved and back your picks.\n\n📲 Find out more — https://www.boylesports.com/promotions/online/football",
          "air": "https://app.air.inc/a/bf5a539f5",
          "boylesports": "https://www.boylesports.com/promotions/online/football",
          "image": "",
          "note": "Scheme GOES LIVE this week; runs Mon-Sun; Air design folder"
        },
        {
          "day": "Monday",
          "match": "Downpatrick - BH Racing",
          "competition": "Horse Racing",
          "promo": "MB 2nd to SP Fav: Downpatrick",
          "type": "Money Back",
          "twitter": "Get your money back as a Free Bet if your horse finishes 2nd to the SP favourite at Downpatrick.\n\nTap below to view the full racecard.",
          "facebook": "",
          "air": "https://app.air.inc/a/bc237ceed/b/0185fb0c-804c-4d07-b5aa-6d2a0f4d3a83",
          "boylesports": "https://www.boylesports.com/sports/horse-racing",
          "image": "",
          "note": "Bank Holiday racing (NI/TG4); IRE/NI only; Week 36 Air folder"
        },
        {
          "day": "Monday",
          "match": "Downpatrick - BH Racing",
          "competition": "Horse Racing",
          "promo": "Extra Places: Downpatrick",
          "type": "Boost / Places",
          "twitter": "We're paying EXTRA PLACES at Downpatrick.\n\nTap below to view the full market.",
          "facebook": "We're paying EXTRA PLACES at Downpatrick.\n\n📲 Full market — https://www.boylesports.com/sports/horse-racing",
          "air": "https://app.air.inc/a/bc237ceed/b/0185fb0c-804c-4d07-b5aa-6d2a0f4d3a83",
          "boylesports": "https://www.boylesports.com/sports/horse-racing",
          "image": "",
          "note": "IRE/NI only; Week 36 Air folder"
        },
        {
          "day": "Monday",
          "match": "Downpatrick - BH Racing",
          "competition": "Horse Racing",
          "promo": "Best Odds Guaranteed: Downpatrick",
          "type": "BOG",
          "twitter": "Best Odds Guaranteed on UK & Irish racing — take an early price and if the SP is bigger, we pay out at the bigger odds.\n\nTap below to view the full racecard.",
          "facebook": "",
          "air": "https://app.air.inc/a/bc237ceed/b/0185fb0c-804c-4d07-b5aa-6d2a0f4d3a83",
          "boylesports": "https://www.boylesports.com/sports/horse-racing",
          "image": "",
          "note": "IRE/NI only; Week 36 Air folder"
        },
        {
          "day": "Monday",
          "match": "US Open Tennis",
          "competition": "Tennis",
          "promo": "Outright Premium Price Boost: US Open",
          "type": "PPB",
          "twitter": "🚀 Outright Premium Price Boost on the US Open Tennis!\n\nTap below to view the market.",
          "facebook": "",
          "air": "https://app.bannerflow.com/studio/brand/5553724f320a791594148995/creativeset/1238259?version=2073355",
          "boylesports": "https://www.boylesports.com/sports/tennis",
          "image": "",
          "note": "US Open runs 31 Aug-6 Sep (Tier 2); outright PPB, no link supplied; PPB Bannerflow creative"
        },
        {
          "day": "Monday",
          "match": "US Open Tennis",
          "competition": "Tennis",
          "promo": "In-Play Bet & Get: US Open (Week 1)",
          "type": "Bet & Get",
          "twitter": "Bet in-play at the US Open Tennis and claim your Free Bet.\n\nTap below to opt in.",
          "facebook": "Bet in-play at the US Open Tennis and claim your Free Bet.\n\n📲 Opt in — https://www.boylesports.com/sports/tennis",
          "air": "https://app.air.inc/a/be0618533",
          "boylesports": "https://www.boylesports.com/sports/tennis",
          "image": "",
          "note": "Week 1 in-play B&G; non-football so no standing link; In-Play B&G Air folder"
        },
        {
          "day": "Monday",
          "match": "British Open",
          "competition": "Snooker",
          "promo": "Outright Price Boost: British Open",
          "type": "Price Boost",
          "twitter": "🚀 Outright Price Boost on the British Open — enhanced odds available now.\n\nTap below to view the market.",
          "facebook": "",
          "air": "https://app.air.inc/a/ba77f1b18",
          "boylesports": "https://www.boylesports.com/sports/snooker",
          "image": "",
          "note": "Snooker (31 Aug-6 Sep); outright price boost"
        },
        {
          "day": "Monday",
          "match": "British Open",
          "competition": "Snooker",
          "promo": "Daily In-Play Bet & Get: British Open",
          "type": "Bet & Get",
          "twitter": "Bet in-play at the British Open and claim your Free Bet.\n\nTap below to opt in.",
          "facebook": "Bet in-play at the British Open and claim your Free Bet.\n\n📲 Opt in — https://www.boylesports.com/sports/snooker",
          "air": "https://app.air.inc/a/ba77f1b18",
          "boylesports": "https://www.boylesports.com/sports/snooker",
          "image": "",
          "note": "Snooker; daily in-play B&G across the week"
        },
        {
          "day": "Tuesday",
          "match": "West Ham Utd v Wolves",
          "competition": "Football",
          "promo": "50% Bet Builder Boost: West Ham Utd v Wolves",
          "type": "50% BBB",
          "twitter": "🚀 Win 50% more with Bet Builder Boost as West Ham Utd lock horns with Wolves.\n\nTap below to view the full market.",
          "facebook": "Win 50% more with Bet Builder Boost as West Ham Utd lock horns with Wolves.\n\n📲 Full market — https://www.boylesports.com/promotions/online/football",
          "air": "https://app.air.inc/a/b66a2bf08",
          "boylesports": "https://www.boylesports.com/promotions/online/football",
          "image": "",
          "note": "Midweek Football; Air design folder"
        },
        {
          "day": "Tuesday",
          "match": "Stoke v Norwich",
          "competition": "Football",
          "promo": "25% Bet Builder Boost: Stoke v Norwich",
          "type": "25% BBB",
          "twitter": "🚀 Win 25% more with Bet Builder Boost as Stoke do battle with Norwich.\n\nTap below to view the full market.",
          "facebook": "Win 25% more with Bet Builder Boost as Stoke do battle with Norwich.\n\n📲 Full market — https://www.boylesports.com/promotions/online/football",
          "air": "https://app.air.inc/a/b0a12f79e",
          "boylesports": "https://www.boylesports.com/promotions/online/football",
          "image": "",
          "note": "Midweek Football; Air design folder"
        },
        {
          "day": "Tuesday",
          "match": "Squad Builder / Bet Builder",
          "competition": "Football",
          "promo": "Bet 5 Get 5 on Squad Builder or Bet Builder",
          "type": "Bet & Get",
          "twitter": "Get a £/€5 Free Bet when you bet £/€5 on a Squad Builder or Bet Builder.\n\nTap below to opt in.",
          "facebook": "Get a £/€5 Free Bet when you bet £/€5 on a Squad Builder or Bet Builder.\n\n📲 Opt in — https://www.boylesports.com/promotions/online/football",
          "air": "https://app.air.inc/a/b9e0dcd43",
          "boylesports": "https://www.boylesports.com/promotions/online/football",
          "image": "",
          "note": "Midweek Football; Air design folder"
        },
        {
          "day": "Wednesday",
          "match": "Burnley v Middlesbrough",
          "competition": "Football",
          "promo": "25% Bet Builder Boost: Burnley v Middlesbrough",
          "type": "25% BBB",
          "twitter": "🚀 Win 25% more with Bet Builder Boost as Burnley face Middlesbrough.\n\nTap below to view the full market.",
          "facebook": "Win 25% more with Bet Builder Boost as Burnley face Middlesbrough.\n\n📲 Full market — https://www.boylesports.com/promotions/online/football",
          "air": "https://app.air.inc/a/b0a12f79e",
          "boylesports": "https://www.boylesports.com/promotions/online/football",
          "image": "",
          "note": "Midweek Football; Air design folder; name per promo list"
        },
        {
          "day": "Wednesday",
          "match": "Celtic v Aberdeen",
          "competition": "Football",
          "promo": "25% Bet Builder Boost: Celtic v Aberdeen",
          "type": "25% BBB",
          "twitter": "🚀 Win 25% more with Bet Builder Boost as Celtic meet Aberdeen.\n\nTap below to view the full market.",
          "facebook": "Win 25% more with Bet Builder Boost as Celtic meet Aberdeen.\n\n📲 Full market — https://www.boylesports.com/promotions/online/football",
          "air": "https://app.air.inc/a/b0a12f79e",
          "boylesports": "https://www.boylesports.com/promotions/online/football",
          "image": "",
          "note": "Midweek Football; Air design folder"
        },
        {
          "day": "Wednesday",
          "match": "Falkirk v Rangers",
          "competition": "Football",
          "promo": "25% Bet Builder Boost: Falkirk v Rangers",
          "type": "25% BBB",
          "twitter": "🚀 Win 25% more with Bet Builder Boost as Falkirk go head-to-head with Rangers.\n\nTap below to view the full market.",
          "facebook": "Win 25% more with Bet Builder Boost as Falkirk go head-to-head with Rangers.\n\n📲 Full market — https://www.boylesports.com/promotions/online/football",
          "air": "https://app.air.inc/a/b0a12f79e",
          "boylesports": "https://www.boylesports.com/promotions/online/football",
          "image": "",
          "note": "Midweek Football; Air design folder"
        },
        {
          "day": "Wednesday",
          "match": "Accas",
          "competition": "Football",
          "promo": "Bet 10 Get 5 on Accas",
          "type": "Bet & Get",
          "twitter": "Get a £/€5 Free Bet when you bet £/€10 on Accas.\n\nTap below to opt in.",
          "facebook": "Get a £/€5 Free Bet when you bet £/€10 on Accas.\n\n📲 Opt in — https://www.boylesports.com/promotions/online/football",
          "air": "https://app.air.inc/a/b622bf4b4",
          "boylesports": "https://www.boylesports.com/promotions/online/football",
          "image": "",
          "note": "Midweek Football; Air design folder"
        },
        {
          "day": "Wednesday",
          "match": "Racing Rewards",
          "competition": "Horse Racing",
          "promo": "Racing Rewards: Bet 10 Get 5 on Multis",
          "type": "Bet & Get",
          "twitter": "Get a £/€5 Free Bet when you bet £/€10 on a multiple.\n\nTap below to opt in.",
          "facebook": "Get a £/€5 Free Bet when you bet £/€10 on a multiple.\n\n📲 Opt in — https://www.boylesports.com/sports/horse-racing",
          "air": "https://app.air.inc/a/b83a701bf/b/e799954a-d115-46ef-b4fc-ff0a885b18a9",
          "boylesports": "https://www.boylesports.com/sports/horse-racing",
          "image": "",
          "note": "IRE/NI only; doubles qualify; runs 2-4 Sep"
        },
        {
          "day": "Thursday",
          "match": "Hibs v Hearts",
          "competition": "Football",
          "promo": "25% Bet Builder Boost: Hibs v Hearts",
          "type": "25% BBB",
          "twitter": "🚀 Win 25% more with Bet Builder Boost as Hibs take on Hearts.\n\nTap below to view the full market.",
          "facebook": "Win 25% more with Bet Builder Boost as Hibs take on Hearts.\n\n📲 Full market — https://www.boylesports.com/promotions/online/football",
          "air": "https://app.air.inc/a/b0a12f79e",
          "boylesports": "https://www.boylesports.com/promotions/online/football",
          "image": "",
          "note": "Midweek Football; Air design folder; name per promo list"
        },
        {
          "day": "Thursday",
          "match": "Real Sociedad v Celta Vigo",
          "competition": "Football",
          "promo": "25% Bet Builder Boost: Real Sociedad v Celta Vigo",
          "type": "25% BBB",
          "twitter": "🚀 Win 25% more with Bet Builder Boost as Real Sociedad face Celta Vigo.\n\nTap below to view the full market.",
          "facebook": "Win 25% more with Bet Builder Boost as Real Sociedad face Celta Vigo.\n\n📲 Full market — https://www.boylesports.com/promotions/online/football",
          "air": "https://app.air.inc/a/b0a12f79e",
          "boylesports": "https://www.boylesports.com/promotions/online/football",
          "image": "",
          "note": "Midweek Football; Air design folder"
        },
        {
          "day": "Thursday",
          "match": "Racing Rewards",
          "competition": "Horse Racing",
          "promo": "Racing Rewards: Bet 10 Get 5 on Multis",
          "type": "Bet & Get",
          "twitter": "Get a £/€5 Free Bet when you bet £/€10 on a multiple.\n\nTap below to opt in.",
          "facebook": "Get a £/€5 Free Bet when you bet £/€10 on a multiple.\n\n📲 Opt in — https://www.boylesports.com/sports/horse-racing",
          "air": "https://app.air.inc/a/b83a701bf/b/e799954a-d115-46ef-b4fc-ff0a885b18a9",
          "boylesports": "https://www.boylesports.com/sports/horse-racing",
          "image": "",
          "note": "IRE/NI only; doubles qualify"
        },
        {
          "day": "Friday",
          "match": "Ipswich v Liverpool",
          "competition": "Football",
          "promo": "Super Boost: Ipswich v Liverpool",
          "type": "Super Boost",
          "twitter": "",
          "facebook": "",
          "air": "https://app.bannerflow.com/studio/brand/5553724f320a791594148995/creativeset/1185282?version=1981413",
          "boylesports": "",
          "image": "",
          "note": "Weekend Football; Squad Builder goes ATL here; football Super Boost creative"
        },
        {
          "day": "Friday",
          "match": "Rovers v Shelbourne",
          "competition": "Football",
          "promo": "Super Boost: LOI - Rovers v Shelbourne",
          "type": "Super Boost",
          "twitter": "",
          "facebook": "",
          "air": "https://app.bannerflow.com/studio/brand/5553724f320a791594148995/creativeset/1185282?version=1981413",
          "boylesports": "",
          "image": "",
          "note": "League of Ireland Friday; football Super Boost creative"
        },
        {
          "day": "Friday",
          "match": "Ipswich v Liverpool",
          "competition": "Football",
          "promo": "25% Bet Builder Boost: Ipswich v Liverpool",
          "type": "25% BBB",
          "twitter": "🚀 Win 25% more with Bet Builder Boost as Ipswich go head-to-head with Liverpool.\n\nTap below to view the full market.",
          "facebook": "Win 25% more with Bet Builder Boost as Ipswich go head-to-head with Liverpool.\n\n📲 Full market — https://www.boylesports.com/promotions/online/football",
          "air": "https://app.air.inc/a/b0a12f79e",
          "boylesports": "https://www.boylesports.com/promotions/online/football",
          "image": "",
          "note": "Weekend Football; Air design folder"
        },
        {
          "day": "Friday",
          "match": "Squad Builder",
          "competition": "Football",
          "promo": "Bet 5 Get 5 on Squad Builder",
          "type": "Bet & Get",
          "twitter": "Get a £/€5 Free Bet when you bet £/€5 on a Squad Builder.\n\nTap below to opt in.",
          "facebook": "Get a £/€5 Free Bet when you bet £/€5 on a Squad Builder.\n\n📲 Opt in — https://www.boylesports.com/promotions/online/football",
          "air": "https://app.air.inc/a/b098a603c/b/03f42df7-eee7-4303-9ba7-82313aa4737b",
          "boylesports": "https://www.boylesports.com/promotions/online/football",
          "image": "",
          "note": "Weekend Football; Squad Builder goes ATL; Air design folder"
        },
        {
          "day": "Friday",
          "match": "Racing Rewards",
          "competition": "Horse Racing",
          "promo": "Racing Rewards: Bet 10 Get 5 on Multis",
          "type": "Bet & Get",
          "twitter": "Get a £/€5 Free Bet when you bet £/€10 on a multiple.\n\nTap below to opt in.",
          "facebook": "Get a £/€5 Free Bet when you bet £/€10 on a multiple.\n\n📲 Opt in — https://www.boylesports.com/sports/horse-racing",
          "air": "https://app.air.inc/a/b83a701bf/b/e799954a-d115-46ef-b4fc-ff0a885b18a9",
          "boylesports": "https://www.boylesports.com/sports/horse-racing",
          "image": "",
          "note": "IRE/NI only; final day of 2-4 Sep run"
        },
        {
          "day": "Friday",
          "match": "Ipswich v Liverpool",
          "competition": "Football",
          "promo": "Free To Play: Ipswich v Liverpool Matchday Challenge",
          "type": "Free To Play",
          "twitter": "Our Matchday Challenge is free to play for Ipswich v Liverpool — make your predictions and play for the jackpot.\n\nTap below to play.",
          "facebook": "",
          "air": "",
          "boylesports": "",
          "image": "",
          "note": "Matchday Challenge FTP jackpot (WIN EUR5K); no link supplied"
        },
        {
          "day": "Saturday",
          "match": "Newcastle v Bournemouth",
          "competition": "Football",
          "promo": "Super Boost: Newcastle v Bournemouth",
          "type": "Super Boost",
          "twitter": "",
          "facebook": "",
          "air": "https://app.bannerflow.com/studio/brand/5553724f320a791594148995/creativeset/1185282?version=1981413",
          "boylesports": "",
          "image": "",
          "note": "Weekend Football; football Super Boost creative"
        },
        {
          "day": "Saturday",
          "match": "Forest v Spurs",
          "competition": "Football",
          "promo": "Super Boost: Forest v Spurs (IRE Only)",
          "type": "Super Boost",
          "twitter": "",
          "facebook": "",
          "air": "https://app.bannerflow.com/studio/brand/5553724f320a791594148995/creativeset/1185282?version=1981413",
          "boylesports": "",
          "image": "",
          "note": "Weekend Football; IRE ONLY; football Super Boost creative"
        },
        {
          "day": "Saturday",
          "match": "Hull v Aston Villa",
          "competition": "Football",
          "promo": "50% Bet Builder Boost: Hull v Aston Villa",
          "type": "50% BBB",
          "twitter": "🚀 Win 50% more with Bet Builder Boost as Hull face Aston Villa.\n\nTap below to view the full market.",
          "facebook": "Win 50% more with Bet Builder Boost as Hull face Aston Villa.\n\n📲 Full market — https://www.boylesports.com/promotions/online/football",
          "air": "https://app.air.inc/a/b66a2bf08",
          "boylesports": "https://www.boylesports.com/promotions/online/football",
          "image": "",
          "note": "Weekend Football; Air design folder"
        },
        {
          "day": "Saturday",
          "match": "St Mirren v Celtic",
          "competition": "Football",
          "promo": "25% Bet Builder Boost: St Mirren v Celtic",
          "type": "25% BBB",
          "twitter": "🚀 Win 25% more with Bet Builder Boost as St Mirren meet Celtic.\n\nTap below to view the full market.",
          "facebook": "Win 25% more with Bet Builder Boost as St Mirren meet Celtic.\n\n📲 Full market — https://www.boylesports.com/promotions/online/football",
          "air": "https://app.air.inc/a/b0a12f79e",
          "boylesports": "https://www.boylesports.com/promotions/online/football",
          "image": "",
          "note": "Weekend Football; Air design folder"
        },
        {
          "day": "Saturday",
          "match": "Brighton v Leeds Utd",
          "competition": "Football",
          "promo": "25% Bet Builder Boost: Brighton v Leeds Utd",
          "type": "25% BBB",
          "twitter": "🚀 Win 25% more with Bet Builder Boost as Brighton go head-to-head with Leeds Utd.\n\nTap below to view the full market.",
          "facebook": "Win 25% more with Bet Builder Boost as Brighton go head-to-head with Leeds Utd.\n\n📲 Full market — https://www.boylesports.com/promotions/online/football",
          "air": "https://app.air.inc/a/b0a12f79e",
          "boylesports": "https://www.boylesports.com/promotions/online/football",
          "image": "",
          "note": "Weekend Football; Air design folder"
        },
        {
          "day": "Saturday",
          "match": "West Ham Utd v Derby County",
          "competition": "Football",
          "promo": "25% Bet Builder Boost: West Ham Utd v Derby County",
          "type": "25% BBB",
          "twitter": "🚀 Win 25% more with Bet Builder Boost as West Ham Utd lock horns with Derby County.\n\nTap below to view the full market.",
          "facebook": "Win 25% more with Bet Builder Boost as West Ham Utd lock horns with Derby County.\n\n📲 Full market — https://www.boylesports.com/promotions/online/football",
          "air": "https://app.air.inc/a/b0a12f79e",
          "boylesports": "https://www.boylesports.com/promotions/online/football",
          "image": "",
          "note": "Weekend Football; Air design folder"
        },
        {
          "day": "Saturday",
          "match": "Nottingham Forest v Tottenham",
          "competition": "Football",
          "promo": "25% Bet Builder Boost: Nottingham Forest v Tottenham",
          "type": "25% BBB",
          "twitter": "🚀 Win 25% more with Bet Builder Boost as Nottingham Forest do battle with Tottenham.\n\nTap below to view the full market.",
          "facebook": "Win 25% more with Bet Builder Boost as Nottingham Forest do battle with Tottenham.\n\n📲 Full market — https://www.boylesports.com/promotions/online/football",
          "air": "https://app.air.inc/a/b0a12f79e",
          "boylesports": "https://www.boylesports.com/promotions/online/football",
          "image": "",
          "note": "Weekend Football; Air design folder; name per promo list"
        },
        {
          "day": "Saturday",
          "match": "Accas",
          "competition": "Football",
          "promo": "Bet 5 Get 5 on Accas",
          "type": "Bet & Get",
          "twitter": "Get a £/€5 Free Bet when you bet £/€5 on Accas.\n\nTap below to opt in.",
          "facebook": "Get a £/€5 Free Bet when you bet £/€5 on Accas.\n\n📲 Opt in — https://www.boylesports.com/promotions/online/football",
          "air": "https://app.air.inc/a/b0676ed5c",
          "boylesports": "https://www.boylesports.com/promotions/online/football",
          "image": "",
          "note": "Weekend Football; Air design folder"
        },
        {
          "day": "Saturday",
          "match": "BOYLE Sports Irish Greyhound Derby SFs",
          "competition": "Greyhounds",
          "promo": "Multi Bet & Get (Bet 10 Get 5): Greyhound Derby SFs",
          "type": "Bet & Get",
          "twitter": "Get a £/€5 Free Bet when you bet £/€10 on a multiple at the BOYLE Sports Irish Greyhound Derby Semi-Finals.\n\nTap below to opt in.",
          "facebook": "Get a £/€5 Free Bet when you bet £/€10 on a multiple at the BOYLE Sports Irish Greyhound Derby Semi-Finals.\n\n📲 Opt in — https://www.boylesports.com/sports/greyhounds",
          "air": "https://app.air.inc/a/b7597427b/b/ccd5fdc8-9a40-4b9a-bc4b-1e4683e3f78b",
          "boylesports": "https://www.boylesports.com/sports/greyhounds",
          "image": "",
          "note": "Sponsored (Tier 2); semi-finals; SBK Air folder"
        },
        {
          "day": "Saturday",
          "match": "BOYLE Sports Irish Greyhound Derby SFs",
          "competition": "Greyhounds",
          "promo": "MB 2nd to SP Fav: Greyhound Derby SFs",
          "type": "Money Back",
          "twitter": "Get your money back as a Free Bet if your dog finishes 2nd to the SP favourite at BOYLE Sports Irish Greyhound Derby Semi-Finals.\n\nTap below to view the full racecard.",
          "facebook": "",
          "air": "https://app.air.inc/a/b7597427b/b/ccd5fdc8-9a40-4b9a-bc4b-1e4683e3f78b",
          "boylesports": "https://www.boylesports.com/sports/greyhounds",
          "image": "",
          "note": "Sponsored; all geos"
        },
        {
          "day": "Saturday",
          "match": "BOYLE Sports Irish Greyhound Derby SFs",
          "competition": "Greyhounds",
          "promo": "Best Odds Guaranteed: Greyhound Derby SFs",
          "type": "BOG",
          "twitter": "Best Odds Guaranteed on Irish greyhound racing — take an early price and if the SP is bigger, we pay out at the bigger odds.\n\nTap below to view the full card.",
          "facebook": "",
          "air": "https://app.air.inc/a/b7597427b/b/ccd5fdc8-9a40-4b9a-bc4b-1e4683e3f78b",
          "boylesports": "https://www.boylesports.com/sports/greyhounds",
          "image": "",
          "note": "Sponsored; all geos"
        },
        {
          "day": "Saturday",
          "match": "Katie Taylor v Pili",
          "competition": "Boxing",
          "promo": "Premium Price Boost: Katie Taylor v Pili (Croke Park)",
          "type": "PPB",
          "twitter": "🚀 Premium Price Boost on Katie Taylor v Pili!\n\nTap below to view the market.",
          "facebook": "",
          "air": "https://app.bannerflow.com/studio/brand/5553724f320a791594148995/creativeset/1238259?version=2073355",
          "boylesports": "https://www.boylesports.com/sports/boxing",
          "image": "",
          "note": "Tier 2 boxing at Croke Park; plan lists PPB but message hierarchy says SUPER BOOST - confirm; PPB Bannerflow creative"
        },
        {
          "day": "Saturday",
          "match": "Constitution Hill - Kempton",
          "competition": "Horse Racing",
          "promo": "Super Boost: Constitution Hill - Kempton",
          "type": "Super Boost",
          "twitter": "",
          "facebook": "",
          "air": "",
          "boylesports": "",
          "image": "",
          "note": "Entry/declaration TBC; non-football Super Boost so no standing link"
        },
        {
          "day": "Sunday",
          "match": "Everton v Man Utd",
          "competition": "Football",
          "promo": "Super Boost: Everton v Man Utd",
          "type": "Super Boost",
          "twitter": "",
          "facebook": "",
          "air": "https://app.bannerflow.com/studio/brand/5553724f320a791594148995/creativeset/1185282?version=1981413",
          "boylesports": "",
          "image": "",
          "note": "Weekend Football (Super Sunday); football Super Boost creative; fixture per promo list"
        },
        {
          "day": "Sunday",
          "match": "Arsenal v Chelsea",
          "competition": "Football",
          "promo": "50% Bet Builder Boost: Arsenal v Chelsea",
          "type": "50% BBB",
          "twitter": "🚀 Win 50% more with Bet Builder Boost as Arsenal do battle with Chelsea.\n\nTap below to view the full market.",
          "facebook": "Win 50% more with Bet Builder Boost as Arsenal do battle with Chelsea.\n\n📲 Full market — https://www.boylesports.com/promotions/online/football",
          "air": "https://app.air.inc/a/b66a2bf08",
          "boylesports": "https://www.boylesports.com/promotions/online/football",
          "image": "",
          "note": "Weekend Football; Air design folder; fixture per promo list"
        },
        {
          "day": "Sunday",
          "match": "Juventus v AC Milan",
          "competition": "Football",
          "promo": "25% Bet Builder Boost: Juventus v AC Milan",
          "type": "25% BBB",
          "twitter": "🚀 Win 25% more with Bet Builder Boost as Juventus take on AC Milan.\n\nTap below to view the full market.",
          "facebook": "Win 25% more with Bet Builder Boost as Juventus take on AC Milan.\n\n📲 Full market — https://www.boylesports.com/promotions/online/football",
          "air": "https://app.air.inc/a/b0a12f79e",
          "boylesports": "https://www.boylesports.com/promotions/online/football",
          "image": "",
          "note": "Weekend Football; Air design folder"
        },
        {
          "day": "Sunday",
          "match": "Squad Builder / Bet Builder",
          "competition": "Football",
          "promo": "Bet 5 Get 5 on Squad Builder or Bet Builder - Super Sunday",
          "type": "Bet & Get",
          "twitter": "Get a £/€5 Free Bet when you bet £/€5 on a Squad Builder or Bet Builder.\n\nTap below to opt in.",
          "facebook": "Get a £/€5 Free Bet when you bet £/€5 on a Squad Builder or Bet Builder.\n\n📲 Opt in — https://www.boylesports.com/promotions/online/football",
          "air": "https://app.air.inc/a/b098a603c/b/3a7f4238-e83f-4303-bc1d-7d3aa4a728e3",
          "boylesports": "https://www.boylesports.com/promotions/online/football",
          "image": "",
          "note": "Weekend Football; Air design folder"
        },
        {
          "day": "Sunday",
          "match": "British Open Final",
          "competition": "Snooker",
          "promo": "Super Boost: British Open Final",
          "type": "Super Boost",
          "twitter": "",
          "facebook": "",
          "air": "https://app.air.inc/a/ba77f1b18",
          "boylesports": "",
          "image": "",
          "note": "Snooker final; non-football Super Boost - uses snooker Air folder"
        },
        {
          "day": "Sunday",
          "match": "Arc Trials Day - Longchamp",
          "competition": "Horse Racing",
          "promo": "Super Boost: Daryz - Arc Trials Day",
          "type": "Super Boost",
          "twitter": "",
          "facebook": "",
          "air": "",
          "boylesports": "",
          "image": "",
          "note": "Longchamp (IRE/NI); Daryz TBC; non-football Super Boost so no standing link"
        },
        {
          "day": "Sunday",
          "match": "Arc Trials Day - Longchamp",
          "competition": "Horse Racing",
          "promo": "MB 2nd to SP Fav: Arc Trials Day",
          "type": "Money Back",
          "twitter": "Get your money back as a Free Bet if your horse finishes 2nd to the SP favourite at Arc Trials Day.\n\nTap below to view the full racecard.",
          "facebook": "",
          "air": "",
          "boylesports": "https://www.boylesports.com/sports/horse-racing",
          "image": "",
          "note": "Longchamp; IRE/NI only"
        }
      ]
    }
  ],
  "gamingWeeks": [
    {
      "label": "31 Aug – 6 Sep 2026",
      "items": [
        {
          "section": "Gaming",
          "name": "1 Million Free Spins Drop",
          "type": "Promotional Post",
          "date": "31 Aug 2026",
          "meta": "🎯🎯1,000,000 Free Spins are dropping across our selected games at BOYLE Casino🎯🎯",
          "twitter": "🎯 1,000,000 Free Spins are dropping across our selected games at BOYLE Casino",
          "instagram": "🎯 1,000,000 Free Spins are dropping across our selected games at BOYLE Casino🎯\n\n📲 Click the link in our bio to learn more.",
          "design": "https://boylesports.sharepoint.com/sites/DesignTeam/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FDesignTeam%2FShared%20Documents%2F00%5FBack%5FYourself%2F03%5FDigital%2F03%5FGAMING%2F13%5FIndividual%20Promotions%2F1%20Million%20Free%20Spins%20Drop%2FPROOF%2FSocial&viewid=1c74581b%2D83eb%2D4158%2D96bc%2Dcbe5821bd850&ga=1",
          "facebook_link": "https://games.boylesports.com/promotions-and-offers/1-million-prizedrop/?btag=55375",
          "twitter_link": "https://games.boylesports.com/promotions-and-offers/1-million-prizedrop/?btag=55376",
          "files": ""
        },
        {
          "section": "Gaming",
          "name": "3 Mad Mummies Hold and Win",
          "type": "New Game Release",
          "date": "1 Sep 2026",
          "meta": "",
          "twitter": "",
          "instagram": "\n\n📲 Click the link in our bio to learn more.",
          "design": "https://app.air.inc/a/bcc24c169/b/51b339c4-a909-4233-ace9-8455eead13b0",
          "facebook_link": "https://games.boylesports.com/games/3-mad-mummies-hold-and-win/",
          "twitter_link": "https://games.boylesports.com/games/3-mad-mummies-hold-and-win/",
          "files": ""
        },
        {
          "section": "Gaming",
          "name": "Sundown Shootout",
          "type": "Gotw",
          "date": "2 Sep 2026",
          "meta": "",
          "twitter": "",
          "instagram": "\n\n📲 Click the link in our bio to learn more.",
          "design": "https://app.air.inc/a/bb67e80ec/b/f5df8a82-c53b-42aa-b9f2-bd2d51ae0446",
          "facebook_link": "https://games.boylesports.com/games/sundown-shootout/",
          "twitter_link": "https://games.boylesports.com/games/sundown-shootout/",
          "files": ""
        },
        {
          "section": "Gaming",
          "name": "Eye of Horus Gold Spins Megaways",
          "type": "New Game Release",
          "date": "3 Sep 2026",
          "meta": "",
          "twitter": "",
          "instagram": "\n\n📲 Click the link in our bio to learn more.",
          "design": "https://app.air.inc/a/bd3cab5a6/b/6541f52b-52a9-4f3a-9149-0a939d0958a0",
          "facebook_link": "https://games.boylesports.com/games/eye-of-horus-gold-spins-megaways/",
          "twitter_link": "https://games.boylesports.com/games/eye-of-horus-gold-spins-megaways/",
          "files": ""
        },
        {
          "section": "Gaming",
          "name": "Bison Canyon Run",
          "type": "Exclusive",
          "date": "4 Sep 2026",
          "meta": "",
          "twitter": "",
          "instagram": "\n\n📲 Click the link in our bio to learn more.",
          "design": "https://app.air.inc/a/b43419469/b/515fa89c-11b4-4a62-8d19-66a5dd2767a9",
          "facebook_link": "https://games.boylesports.com/games/bison-canyon-run/",
          "twitter_link": "https://games.boylesports.com/games/bison-canyon-run/",
          "files": ""
        },
        {
          "section": "Live Casino",
          "name": "Fortune Roulette Live",
          "type": "Highlighted game",
          "date": "5 Sep 2026",
          "meta": "✨✨BOYLE Live Casino presents FORTUNE ROULETTE LIVE✨ ✨",
          "twitter": "✨ BOYLE Live Casino presents FORTUNE ROULETTE LIVE",
          "instagram": "✨ BOYLE Live Casino presents FORTUNE ROULETTE LIVE✨\n\n📲 Click the link in our bio to learn more.",
          "design": "https://app.air.inc/a/bf89006ea",
          "facebook_link": "https://games.boylesports.com/games/fortune-roulette-live/?btag=55400",
          "twitter_link": "https://games.boylesports.com/games/fortune-roulette-live/?btag=55401",
          "files": ""
        },
        {
          "section": "Live Casino",
          "name": "Quantum Energy!",
          "type": "Potpourri",
          "date": "6 Sep 2026",
          "meta": "",
          "twitter": "",
          "instagram": "\n\n📲 Click the link in our bio to learn more.",
          "design": "https://app.air.inc/a/b9aa28aaa",
          "facebook_link": "https://games.boylesports.com/live-casino/?btag=55400",
          "twitter_link": "https://games.boylesports.com/live-casino/?btag=55401",
          "files": ""
        }
      ]
    }
  ],
  "campaign": {
    "title": "World Cup Campaign",
    "note": "World Cup Live · 11 Jun – 19 Jul 2026",
    "months": [
      "2026-06",
      "2026-07"
    ],
    "fixtures": [
      {
        "date": "2026-06-11",
        "homeAbbr": "MEX",
        "awayAbbr": "SA",
        "home": "Mexico",
        "away": "South Africa",
        "time": "8pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-12",
        "homeAbbr": "CAN",
        "awayAbbr": "BOS",
        "home": "Canada",
        "away": "Bosnia",
        "time": "8pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-13",
        "homeAbbr": "HAI",
        "awayAbbr": "SCO",
        "home": "Haiti",
        "away": "Scotland",
        "time": "2am",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-14",
        "homeAbbr": "GER",
        "awayAbbr": "CUR",
        "home": "Germany",
        "away": "Curaçao",
        "time": "6pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-15",
        "homeAbbr": "BEL",
        "awayAbbr": "EGY",
        "home": "Belgium",
        "away": "Egypt",
        "time": "8pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-16",
        "homeAbbr": "FRA",
        "awayAbbr": "SEN",
        "home": "France",
        "away": "Senegal",
        "time": "8pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-17",
        "homeAbbr": "ENG",
        "awayAbbr": "CRO",
        "home": "England",
        "away": "Croatia",
        "time": "9pm",
        "time2": "",
        "eng": true
      },
      {
        "date": "2026-06-18",
        "homeAbbr": "SWI",
        "awayAbbr": "BOS",
        "home": "Switzerland",
        "away": "Bosnia",
        "time": "8pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-19",
        "homeAbbr": "SCO",
        "awayAbbr": "MOR",
        "home": "Scotland",
        "away": "Morocco",
        "time": "11pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-20",
        "homeAbbr": "NED",
        "awayAbbr": "SWE",
        "home": "Netherlands",
        "away": "Sweden",
        "time": "6pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-21",
        "homeAbbr": "SPA",
        "awayAbbr": "SAU",
        "home": "Spain",
        "away": "Saudi Arabia",
        "time": "5pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-22",
        "homeAbbr": "ARG",
        "awayAbbr": "AUS",
        "home": "Argentina",
        "away": "Australia",
        "time": "6pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-23",
        "homeAbbr": "ENG",
        "awayAbbr": "GHA",
        "home": "England",
        "away": "Ghana",
        "time": "9pm",
        "time2": "",
        "eng": true
      },
      {
        "date": "2026-06-24",
        "homeAbbr": "SCO",
        "awayAbbr": "BRA",
        "home": "Scotland",
        "away": "Brazil",
        "time": "11pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-25",
        "homeAbbr": "ECU",
        "awayAbbr": "GER",
        "home": "Ecuador",
        "away": "Germany",
        "time": "9pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-26",
        "homeAbbr": "NOR",
        "awayAbbr": "FRA",
        "home": "Norway",
        "away": "France",
        "time": "8pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-27",
        "homeAbbr": "ENG",
        "awayAbbr": "PAN",
        "home": "England",
        "away": "Panama",
        "time": "10pm",
        "time2": "",
        "eng": true
      },
      {
        "date": "2026-06-28",
        "homeAbbr": "?",
        "awayAbbr": "?",
        "home": "TBC",
        "away": "TBC",
        "time": "8pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-29",
        "homeAbbr": "?",
        "awayAbbr": "?",
        "home": "TBC",
        "away": "TBC",
        "time": "6pm",
        "time2": "9pm",
        "eng": false
      },
      {
        "date": "2026-06-30",
        "homeAbbr": "?",
        "awayAbbr": "?",
        "home": "TBC",
        "away": "TBC",
        "time": "6pm",
        "time2": "10pm",
        "eng": false
      },
      {
        "date": "2026-07-01",
        "homeAbbr": "ENG?",
        "awayAbbr": "?",
        "home": "England?",
        "away": "TBC",
        "time": "5pm",
        "time2": "",
        "eng": true
      },
      {
        "date": "2026-07-02",
        "homeAbbr": "?",
        "awayAbbr": "?",
        "home": "TBC",
        "away": "TBC",
        "time": "8pm",
        "time2": "12am",
        "eng": false
      },
      {
        "date": "2026-07-03",
        "homeAbbr": "?",
        "awayAbbr": "?",
        "home": "TBC",
        "away": "TBC",
        "time": "7pm",
        "time2": "11pm",
        "eng": false
      },
      {
        "date": "2026-07-04",
        "homeAbbr": "?",
        "awayAbbr": "?",
        "home": "TBC",
        "away": "TBC",
        "time": "6pm",
        "time2": "10pm",
        "eng": false
      },
      {
        "date": "2026-07-05",
        "homeAbbr": "ENG?",
        "awayAbbr": "?",
        "home": "England?",
        "away": "TBC",
        "time": "1am",
        "time2": "",
        "eng": true
      },
      {
        "date": "2026-07-06",
        "homeAbbr": "?",
        "awayAbbr": "?",
        "home": "TBC",
        "away": "TBC",
        "time": "8pm",
        "time2": "1am",
        "eng": false
      },
      {
        "date": "2026-07-07",
        "homeAbbr": "?",
        "awayAbbr": "?",
        "home": "TBC",
        "away": "TBC",
        "time": "5pm",
        "time2": "9pm",
        "eng": false
      },
      {
        "date": "2026-07-09",
        "homeAbbr": "?",
        "awayAbbr": "?",
        "home": "TBC",
        "away": "TBC",
        "time": "9pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-07-10",
        "homeAbbr": "?",
        "awayAbbr": "?",
        "home": "TBC",
        "away": "TBC",
        "time": "8pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-07-11",
        "homeAbbr": "ENG?",
        "awayAbbr": "?",
        "home": "England?",
        "away": "TBC",
        "time": "10pm",
        "time2": "",
        "eng": true
      },
      {
        "date": "2026-07-14",
        "homeAbbr": "?",
        "awayAbbr": "?",
        "home": "TBC",
        "away": "TBC",
        "time": "8pm",
        "time2": "-",
        "eng": false
      },
      {
        "date": "2026-07-15",
        "homeAbbr": "ENG?",
        "awayAbbr": "?",
        "home": "England?",
        "away": "TBC",
        "time": "8pm",
        "time2": "",
        "eng": true
      },
      {
        "date": "2026-07-19",
        "homeAbbr": "ENG?",
        "awayAbbr": "?",
        "home": "England?",
        "away": "TBC",
        "time": "8pm",
        "time2": "",
        "eng": true
      }
    ],
    "events": [
      {
        "date": "2026-06-03",
        "cat": "launch",
        "title": "Olivia Launch",
        "sub": "‘Welcome to the Team’ — photos, press release & piece to camera",
        "marker": "OUT"
      },
      {
        "date": "2026-06-04",
        "cat": "talent",
        "title": "Glen Hoddle",
        "sub": "Guest Talent / OB",
        "marker": "OUT"
      },
      {
        "date": "2026-06-12",
        "cat": "talent",
        "title": "Gary McAllister",
        "sub": "Guest Talent / OB",
        "marker": "OUT"
      },
      {
        "date": "2026-06-25",
        "cat": "talent",
        "title": "Stuart Pearce",
        "sub": "Guest Talent / OB",
        "marker": "OUT"
      },
      {
        "date": "2026-06-08",
        "cat": "buz",
        "title": "The Buz — England v Croatia: Key Battles?",
        "sub": "Piece to camera",
        "marker": "RECORD"
      },
      {
        "date": "2026-06-09",
        "cat": "buz",
        "title": "The Buz — England v Croatia: Key Battles?",
        "sub": "Piece to camera",
        "marker": "OUT"
      },
      {
        "date": "2026-06-15",
        "cat": "buz",
        "title": "The Buz — Scotland/Morocco & Holland/Sweden talking points",
        "sub": "Piece to camera",
        "marker": "RECORD"
      },
      {
        "date": "2026-06-16",
        "cat": "buz",
        "title": "The Buz — Scotland/Morocco & Holland/Sweden talking points",
        "sub": "Piece to camera",
        "marker": "OUT"
      },
      {
        "date": "2026-06-22",
        "cat": "buz",
        "title": "The Buz — Weekly (topic TBC)",
        "sub": "Piece to camera",
        "marker": "RECORD"
      },
      {
        "date": "2026-06-23",
        "cat": "buz",
        "title": "The Buz — Weekly (topic TBC)",
        "sub": "Piece to camera",
        "marker": "OUT"
      },
      {
        "date": "2026-06-29",
        "cat": "buz",
        "title": "The Buz — Weekly (topic TBC)",
        "sub": "Piece to camera",
        "marker": "RECORD"
      },
      {
        "date": "2026-06-30",
        "cat": "buz",
        "title": "The Buz — Weekly (topic TBC)",
        "sub": "Piece to camera",
        "marker": "OUT"
      },
      {
        "date": "2026-07-06",
        "cat": "buz",
        "title": "The Buz — Weekly (topic TBC)",
        "sub": "Piece to camera",
        "marker": "RECORD"
      },
      {
        "date": "2026-07-07",
        "cat": "buz",
        "title": "The Buz — Weekly (topic TBC)",
        "sub": "Piece to camera",
        "marker": "OUT"
      },
      {
        "date": "2026-07-13",
        "cat": "buz",
        "title": "The Buz — Weekly (topic TBC)",
        "sub": "Piece to camera",
        "marker": "RECORD"
      },
      {
        "date": "2026-07-14",
        "cat": "buz",
        "title": "The Buz — Weekly (topic TBC)",
        "sub": "Piece to camera",
        "marker": "OUT"
      },
      {
        "date": "2026-06-17",
        "cat": "fan",
        "title": "Fan Forecast",
        "sub": "Host: Olivia · Dallas",
        "marker": "OUT"
      },
      {
        "date": "2026-06-23",
        "cat": "fan",
        "title": "Fan Forecast",
        "sub": "Host: JCC/Maz/Zac · London (London Bridge)",
        "marker": "OUT"
      },
      {
        "date": "2026-06-24",
        "cat": "fan",
        "title": "Fan Forecast",
        "sub": "Host: JCC/Maz/Zac · London (London Bridge)",
        "marker": "OUT"
      },
      {
        "date": "2026-06-27",
        "cat": "fan",
        "title": "Fan Forecast",
        "sub": "Host: JCC/Maz/Zac · London (London Bridge)",
        "marker": "OUT"
      },
      {
        "date": "2026-07-01",
        "cat": "fan",
        "title": "Fan Forecast",
        "sub": "Host: JCC/Maz/Zac · London",
        "marker": "TBC"
      },
      {
        "date": "2026-07-05",
        "cat": "fan",
        "title": "Fan Forecast",
        "sub": "Host: JCC/Maz/Zac · London",
        "marker": "TBC"
      },
      {
        "date": "2026-07-11",
        "cat": "fan",
        "title": "Fan Forecast",
        "sub": "Host: JCC/Maz/Zac · London",
        "marker": "TBC"
      },
      {
        "date": "2026-07-15",
        "cat": "fan",
        "title": "Fan Forecast",
        "sub": "Host: JCC/Maz/Zac · London",
        "marker": "TBC"
      },
      {
        "date": "2026-07-19",
        "cat": "fan",
        "title": "Fan Forecast",
        "sub": "Host: JCC/Maz/Zac · London",
        "marker": "TBC"
      }
    ]
  }
};
