// Social Content Hub — weekly data. GENERATED by build/build_data.py. Do not hand-edit.
window.SCH_DATA = {
  "weeks": [
    {
      "label": "10–16 Aug 2026",
      "commencing": "2026-08-10",
      "theme": "Gaming line-up in — promotions & schedule to follow",
      "updated": "2026-08-09",
      "priorities": [],
      "schedule": []
    },
    {
      "label": "17–23 Aug 2026",
      "commencing": "2026-08-17",
      "theme": "Gaming line-up in — promotions & schedule to follow",
      "updated": "2026-08-14",
      "priorities": [],
      "schedule": []
    }
  ],
  "links": [
    {
      "label": "Air (Imagery)",
      "url": "https://app.air.inc"
    },
    {
      "label": "BoyleSports Sports",
      "url": "https://www.boylesports.com/sports/football"
    },
    {
      "label": "BoyleSports Casino",
      "url": "https://games.boylesports.com"
    },
    {
      "label": "Brandwatch",
      "url": "https://www.brandwatch.com/"
    }
  ],
  "promoWeeks": [
    {
      "label": "10–16 Aug 2026",
      "items": []
    },
    {
      "label": "17–23 Aug 2026",
      "items": []
    }
  ],
  "gamingWeeks": [
    {
      "label": "10–16 Aug 2026",
      "items": [
        {
          "section": "Gaming",
          "name": "Prag Wheel - 500K / Prag Tournament.",
          "type": "Promotional Post",
          "date": "10 Aug 2026",
          "meta": "☀️☀️ Claim Up to 100 Free Spins at BOYLE Casino 👉Join Tournament & Wheel Drops for a share of £/€50K in Cash & Free Spins.",
          "twitter": "☀️ Claim Up to 100 Free Spins at BOYLE Casino Join Tournament & Wheel Drops for a share of £/€50K in Cash & Free Spins.",
          "instagram": "☀️ Claim Up to 100 Free Spins at BOYLE Casino 👉Join Tournament & Wheel Drops for a share of £/€50K in Cash & Free Spins.\n\n📲 Click the link in our bio to learn more.",
          "design": "https://app.air.inc/a/b4521bf84/b/aba6d7a8-321e-4c1b-b16a-ba8dd6ff5060",
          "facebook_link": "https://games.boylesports.com/promotions-and-offers/wheels-leaderboard/?btag=56100",
          "twitter_link": "https://games.boylesports.com/promotions-and-offers/wheels-leaderboard/?btag=56101",
          "files": ""
        },
        {
          "section": "Live Casino",
          "name": "London Roulette Live",
          "type": "New Game Release",
          "date": "10 Aug 2026",
          "meta": "🆕🆕 New Game Release at Boyle Live Casino! 🆕🆕  London Roulette Live",
          "twitter": "🆕 New Game Release at Boyle Live Casino! London Roulette Live",
          "instagram": "🆕 New Game Release at Boyle Live Casino! 🆕  London Roulette Live\n\n📲 Click the link in our bio to learn more.",
          "design": "https://app.air.inc/a/b89845cb9/b/2509d780-037f-4193-acab-5f12089c4db9",
          "facebook_link": "https://games.boylesports.com/games/london-roulette-live/?btag=55400",
          "twitter_link": "https://games.boylesports.com/games/london-roulette-live/?btag=55401",
          "files": ""
        },
        {
          "section": "Gaming",
          "name": "Prospector Wilds Hold and Blitz",
          "type": "New Game Release",
          "date": "11 Aug 2026",
          "meta": "🤩🤩New Game Release at BOYLE Casino! 🤩🤩",
          "twitter": "🤩 New Game Release at BOYLE Casino!",
          "instagram": "🤩 New Game Release at BOYLE Casino! 🤩\n\n📲 Click the link in our bio to learn more.",
          "design": "https://app.air.inc/a/b4814976b/b/9f425d09-6bf1-4ff2-9bd8-22296f1c991e",
          "facebook_link": "https://games.boylesports.com/games/Prospector-Wilds-Hold-and-Blitz/?btag=52901",
          "twitter_link": "https://games.boylesports.com/games/Prospector-Wilds-Hold-and-Blitz/?btag=52962",
          "files": ""
        },
        {
          "section": "Gaming",
          "name": "Cash Strike Fire Lock",
          "type": "New Game Release",
          "date": "12 Aug 2026",
          "meta": "🤩🤩New Game Release at BOYLE Casino! 🤩🤩",
          "twitter": "🤩 New Game Release at BOYLE Casino!",
          "instagram": "🤩 New Game Release at BOYLE Casino! 🤩\n\n📲 Click the link in our bio to learn more.",
          "design": "https://app.air.inc/a/bc6020d9a/b/1a323034-2a10-4a22-bb94-27829c1f653e",
          "facebook_link": "https://games.boylesports.com/games/Cash-Strike-Fire-Lock/?btag=52901",
          "twitter_link": "https://games.boylesports.com/games/Cash-Strike-Fire-Lock/?btag=52962",
          "files": ""
        },
        {
          "section": "Gaming",
          "name": "Lemon Squeezy",
          "type": "New Game Release",
          "date": "13 Aug 2026",
          "meta": "🤩🤩New Game Release at BOYLE Casino! 🤩🤩",
          "twitter": "🤩 New Game Release at BOYLE Casino!",
          "instagram": "🤩 New Game Release at BOYLE Casino! 🤩\n\n📲 Click the link in our bio to learn more.",
          "design": "https://app.air.inc/a/b2a40ff7b/b/e73bec60-b31c-4e85-8805-0c7fbdb9eae7",
          "facebook_link": "https://games.boylesports.com/games/Lemon-Squeezy/?btag=52901",
          "twitter_link": "https://games.boylesports.com/games/Lemon-Squeezy/?btag=52962",
          "files": ""
        },
        {
          "section": "Live Casino",
          "name": "London Blackjack Live",
          "type": "New Game Release",
          "date": "13 Aug 2026",
          "meta": "🆕🆕 New Game Release at Boyle Live Casino! 🆕🆕  London Blackjack Live",
          "twitter": "🆕 New Game Release at Boyle Live Casino! London Blackjack Live",
          "instagram": "🆕 New Game Release at Boyle Live Casino! 🆕  London Blackjack Live\n\n📲 Click the link in our bio to learn more.",
          "design": "https://app.air.inc/a/b19b781a5",
          "facebook_link": "https://games.boylesports.com/games/london-blackjack-live/?btag=55400",
          "twitter_link": "https://games.boylesports.com/games/london-blackjack-live/?btag=55401",
          "files": ""
        },
        {
          "section": "Gaming",
          "name": "The Devil's Draw",
          "type": "Gotw",
          "date": "14 Aug 2026",
          "meta": "✨✨Game of the Week at BOYLE Casino! ✨✨",
          "twitter": "✨ Game of the Week at BOYLE Casino!",
          "instagram": "✨ Game of the Week at BOYLE Casino! ✨\n\n📲 Click the link in our bio to learn more.",
          "design": "https://app.air.inc/a/bf3bbadd7/b/358f2ca5-6777-4e4a-be00-546ed9e12942",
          "facebook_link": "https://games.boylesports.com/games/the-devils-draw/?btag=52901",
          "twitter_link": "https://games.boylesports.com/games/the-devils-draw/?btag=52962",
          "files": ""
        },
        {
          "section": "Live Casino",
          "name": "Hippodrome Live Roulette",
          "type": "New Game Release",
          "date": "15 Aug 2026",
          "meta": "🆕🆕 New Game Release at Boyle Live Casino! 🆕🆕  Hippodrome London Roulette Live",
          "twitter": "🆕 New Game Release at Boyle Live Casino! Hippodrome London Roulette Live",
          "instagram": "🆕 New Game Release at Boyle Live Casino! 🆕  Hippodrome London Roulette Live\n\n📲 Click the link in our bio to learn more.",
          "design": "",
          "facebook_link": "https://games.boylesports.com/games/hippodrome-live-roulette/?btag=55400",
          "twitter_link": "https://games.boylesports.com/games/hippodrome-live-roulette/?btag=55401",
          "files": ""
        },
        {
          "section": "Live Casino",
          "name": "Light's on, it's showtime!",
          "type": "Potpourri",
          "date": "16 Aug 2026",
          "meta": "🎬🎭 Lights, camera, action! Discover live game shows at Boyle Live Casino 🎬🎭",
          "twitter": "🎬 Lights, camera, action! Discover live game shows at Boyle Live Casino",
          "instagram": "🎬🎭 Lights, camera, action! Discover live game shows at Boyle Live Casino 🎬🎭\n\n📲 Click the link in our bio to learn more.",
          "design": "",
          "facebook_link": "https://games.boylesports.com/live-game-shows/?btag=55400",
          "twitter_link": "https://games.boylesports.com/live-game-shows/?btag=55401",
          "files": ""
        }
      ]
    },
    {
      "label": "17–23 Aug 2026",
      "items": [
        {
          "section": "Gaming",
          "name": "25K Giveaway",
          "type": "Promotional Post",
          "date": "17 Aug 2026",
          "meta": "🎯🎯Jump in for your chance to land a share of our 25K cash prize pot🎯🎯",
          "twitter": "🎯 Jump in for your chance to land a share of our 25K cash prize pot",
          "instagram": "🎯 Jump in for your chance to land a share of our 25K cash prize pot🎯\n\n📲 Click the link in our bio to learn more.",
          "design": "https://boylesports.sharepoint.com/sites/DesignTeam/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FDesignTeam%2FShared%20Documents%2F00%5FBack%5FYourself%2F03%5FDigital%2F03%5FGAMING%2F12%5FGiveaways%2F25K%20Giveaway%20Playngo%2FPROOF%2FSocial&viewid=1c74581b%2D83eb%2D4158%2D96bc%2Dcbe5821bd850&ga=1",
          "facebook_link": "https://games.boylesports.com/promotions-and-offers/25k-giveaway/?btag=55299",
          "twitter_link": "https://games.boylesports.com/promotions-and-offers/25k-giveaway/?btag=55300",
          "files": ""
        },
        {
          "section": "Gaming",
          "name": "4 Supershiny Diamonds Hold and Win",
          "type": "New Game Release",
          "date": "18 Aug 2026",
          "meta": "🤩🤩New Game Release at BOYLE Casino! 🤩🤩",
          "twitter": "🤩 New Game Release at BOYLE Casino!",
          "instagram": "🤩 New Game Release at BOYLE Casino! 🤩\n\n📲 Click the link in our bio to learn more.",
          "design": "https://app.air.inc/a/bb4279b83/b/7509f65d-94c2-4fb8-a1b0-5faaa511dcf2",
          "facebook_link": "https://games.boylesports.com/games/4-Supershiny-Diamonds-Hold-and-Win/?btag=52901",
          "twitter_link": "https://games.boylesports.com/games/4-Supershiny-Diamonds-Hold-and-Win/?btag=52962",
          "files": ""
        },
        {
          "section": "Gaming",
          "name": "Legends of the Lure",
          "type": "Trending Slot",
          "date": "19 Aug 2026",
          "meta": "🚀🚀Check out this month's Trending slot at BOYLE Casino!!👀",
          "twitter": "🚀 Check out this month's Trending slot at BOYLE Casino!!",
          "instagram": "🚀 Check out this month's Trending slot at BOYLE Casino!!👀\n\n📲 Click the link in our bio to learn more.",
          "design": "https://boylesports.sharepoint.com/sites/DesignTeam/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FDesignTeam%2FShared%20Documents%2F00%5FBack%5FYourself%2F05%5FVideo%2F02%5FGaming%2FTrending%20slots%2FLegends%20of%20the%20Lure&p=true&ga=1&or=EXCEL%2DWEB%2EBODY%2ENT&ct=1779953919017&OR=EXCEL%2DWEB%2EBODY%2ENT&CT=1784275172294",
          "facebook_link": "https://games.boylesports.com/games/legends-of-the-lure/?btag=52901",
          "twitter_link": "https://games.boylesports.com/games/legends-of-the-lure/?btag=52962",
          "files": ""
        },
        {
          "section": "Gaming",
          "name": "7x7 Zeus Max",
          "type": "Exclusive",
          "date": "20 Aug 2026",
          "meta": "🔥🔥EXCLUSIVE Game at BOYLE Casino! 🔥🔥",
          "twitter": "🔥 EXCLUSIVE Game at BOYLE Casino!",
          "instagram": "🔥 EXCLUSIVE Game at BOYLE Casino! 🔥\n\n📲 Click the link in our bio to learn more.",
          "design": "https://app.air.inc/a/b534f216e/b/ef3d1e55-d68a-43af-97b3-5a2185b367aa",
          "facebook_link": "https://games.boylesports.com/games/7x7-Zeus-Max/?btag=52901",
          "twitter_link": "https://games.boylesports.com/games/7x7-Zeus-Max/?btag=52962",
          "files": ""
        },
        {
          "section": "Gaming",
          "name": "Captain Jacks Voyage",
          "type": "New Game Release",
          "date": "21 Aug 2026",
          "meta": "🤩🤩New Game Release at BOYLE Casino! 🤩🤩",
          "twitter": "🤩 New Game Release at BOYLE Casino!",
          "instagram": "🤩 New Game Release at BOYLE Casino! 🤩\n\n📲 Click the link in our bio to learn more.",
          "design": "https://app.air.inc/a/beddef67e/b/fa77991c-2f91-4377-a912-11e23498d968",
          "facebook_link": "https://games.boylesports.com/games/Captain-Jacks-Voyage/?btag=52901",
          "twitter_link": "https://games.boylesports.com/games/Captain-Jacks-Voyage/?btag=52962",
          "files": ""
        },
        {
          "section": "Live Casino",
          "name": "Gates of Olympus Roulette Live",
          "type": "Highlighted game",
          "date": "22 Aug 2026",
          "meta": "✨✨BOYLE Live Casino presents GATES OF OLYMPUS ✨ ✨",
          "twitter": "✨ BOYLE Live Casino presents GATES OF OLYMPUS",
          "instagram": "✨ BOYLE Live Casino presents GATES OF OLYMPUS ✨\n\n📲 Click the link in our bio to learn more.",
          "design": "",
          "facebook_link": "https://games.boylesports.com/games/gates-of-olympus-roulette-live/?btag=55400",
          "twitter_link": "https://games.boylesports.com/games/gates-of-olympus-roulette-live/?btag=55401",
          "files": ""
        },
        {
          "section": "Live Casino",
          "name": "Roulette Potpourri version 1",
          "type": "Potpourri",
          "date": "23 Aug 2026",
          "meta": "🎡🎡 Ready to spin? Enjoy our fantastic roulettes with real dealers at Boyle Live Casino 🎡🎡",
          "twitter": "🎡 Ready to spin? Enjoy our fantastic roulettes with real dealers at Boyle Live Casino",
          "instagram": "🎡 Ready to spin? Enjoy our fantastic roulettes with real dealers at Boyle Live Casino 🎡\n\n📲 Click the link in our bio to learn more.",
          "design": "https://app.air.inc/a/bf9c335eb",
          "facebook_link": "https://games.boylesports.com/live-roulette/?btag=55400",
          "twitter_link": "https://games.boylesports.com/live-roulette/?btag=55401",
          "files": ""
        }
      ]
    }
  ],
  "campaign": {
    "title": "World Cup Campaign",
    "note": "World Cup Live · 11 Jun – 19 Jul 2026",
    "months": [
      "2026-06",
      "2026-07"
    ],
    "fixtures": [
      {
        "date": "2026-06-11",
        "homeAbbr": "MEX",
        "awayAbbr": "SA",
        "home": "Mexico",
        "away": "South Africa",
        "time": "8pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-12",
        "homeAbbr": "CAN",
        "awayAbbr": "BOS",
        "home": "Canada",
        "away": "Bosnia",
        "time": "8pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-13",
        "homeAbbr": "HAI",
        "awayAbbr": "SCO",
        "home": "Haiti",
        "away": "Scotland",
        "time": "2am",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-14",
        "homeAbbr": "GER",
        "awayAbbr": "CUR",
        "home": "Germany",
        "away": "Curaçao",
        "time": "6pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-15",
        "homeAbbr": "BEL",
        "awayAbbr": "EGY",
        "home": "Belgium",
        "away": "Egypt",
        "time": "8pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-16",
        "homeAbbr": "FRA",
        "awayAbbr": "SEN",
        "home": "France",
        "away": "Senegal",
        "time": "8pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-17",
        "homeAbbr": "ENG",
        "awayAbbr": "CRO",
        "home": "England",
        "away": "Croatia",
        "time": "9pm",
        "time2": "",
        "eng": true
      },
      {
        "date": "2026-06-18",
        "homeAbbr": "SWI",
        "awayAbbr": "BOS",
        "home": "Switzerland",
        "away": "Bosnia",
        "time": "8pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-19",
        "homeAbbr": "SCO",
        "awayAbbr": "MOR",
        "home": "Scotland",
        "away": "Morocco",
        "time": "11pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-20",
        "homeAbbr": "NED",
        "awayAbbr": "SWE",
        "home": "Netherlands",
        "away": "Sweden",
        "time": "6pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-21",
        "homeAbbr": "SPA",
        "awayAbbr": "SAU",
        "home": "Spain",
        "away": "Saudi Arabia",
        "time": "5pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-22",
        "homeAbbr": "ARG",
        "awayAbbr": "AUS",
        "home": "Argentina",
        "away": "Australia",
        "time": "6pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-23",
        "homeAbbr": "ENG",
        "awayAbbr": "GHA",
        "home": "England",
        "away": "Ghana",
        "time": "9pm",
        "time2": "",
        "eng": true
      },
      {
        "date": "2026-06-24",
        "homeAbbr": "SCO",
        "awayAbbr": "BRA",
        "home": "Scotland",
        "away": "Brazil",
        "time": "11pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-25",
        "homeAbbr": "ECU",
        "awayAbbr": "GER",
        "home": "Ecuador",
        "away": "Germany",
        "time": "9pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-26",
        "homeAbbr": "NOR",
        "awayAbbr": "FRA",
        "home": "Norway",
        "away": "France",
        "time": "8pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-27",
        "homeAbbr": "ENG",
        "awayAbbr": "PAN",
        "home": "England",
        "away": "Panama",
        "time": "10pm",
        "time2": "",
        "eng": true
      },
      {
        "date": "2026-06-28",
        "homeAbbr": "?",
        "awayAbbr": "?",
        "home": "TBC",
        "away": "TBC",
        "time": "8pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-06-29",
        "homeAbbr": "?",
        "awayAbbr": "?",
        "home": "TBC",
        "away": "TBC",
        "time": "6pm",
        "time2": "9pm",
        "eng": false
      },
      {
        "date": "2026-06-30",
        "homeAbbr": "?",
        "awayAbbr": "?",
        "home": "TBC",
        "away": "TBC",
        "time": "6pm",
        "time2": "10pm",
        "eng": false
      },
      {
        "date": "2026-07-01",
        "homeAbbr": "ENG?",
        "awayAbbr": "?",
        "home": "England?",
        "away": "TBC",
        "time": "5pm",
        "time2": "",
        "eng": true
      },
      {
        "date": "2026-07-02",
        "homeAbbr": "?",
        "awayAbbr": "?",
        "home": "TBC",
        "away": "TBC",
        "time": "8pm",
        "time2": "12am",
        "eng": false
      },
      {
        "date": "2026-07-03",
        "homeAbbr": "?",
        "awayAbbr": "?",
        "home": "TBC",
        "away": "TBC",
        "time": "7pm",
        "time2": "11pm",
        "eng": false
      },
      {
        "date": "2026-07-04",
        "homeAbbr": "?",
        "awayAbbr": "?",
        "home": "TBC",
        "away": "TBC",
        "time": "6pm",
        "time2": "10pm",
        "eng": false
      },
      {
        "date": "2026-07-05",
        "homeAbbr": "ENG?",
        "awayAbbr": "?",
        "home": "England?",
        "away": "TBC",
        "time": "1am",
        "time2": "",
        "eng": true
      },
      {
        "date": "2026-07-06",
        "homeAbbr": "?",
        "awayAbbr": "?",
        "home": "TBC",
        "away": "TBC",
        "time": "8pm",
        "time2": "1am",
        "eng": false
      },
      {
        "date": "2026-07-07",
        "homeAbbr": "?",
        "awayAbbr": "?",
        "home": "TBC",
        "away": "TBC",
        "time": "5pm",
        "time2": "9pm",
        "eng": false
      },
      {
        "date": "2026-07-09",
        "homeAbbr": "?",
        "awayAbbr": "?",
        "home": "TBC",
        "away": "TBC",
        "time": "9pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-07-10",
        "homeAbbr": "?",
        "awayAbbr": "?",
        "home": "TBC",
        "away": "TBC",
        "time": "8pm",
        "time2": "",
        "eng": false
      },
      {
        "date": "2026-07-11",
        "homeAbbr": "ENG?",
        "awayAbbr": "?",
        "home": "England?",
        "away": "TBC",
        "time": "10pm",
        "time2": "",
        "eng": true
      },
      {
        "date": "2026-07-14",
        "homeAbbr": "?",
        "awayAbbr": "?",
        "home": "TBC",
        "away": "TBC",
        "time": "8pm",
        "time2": "-",
        "eng": false
      },
      {
        "date": "2026-07-15",
        "homeAbbr": "ENG?",
        "awayAbbr": "?",
        "home": "England?",
        "away": "TBC",
        "time": "8pm",
        "time2": "",
        "eng": true
      },
      {
        "date": "2026-07-19",
        "homeAbbr": "ENG?",
        "awayAbbr": "?",
        "home": "England?",
        "away": "TBC",
        "time": "8pm",
        "time2": "",
        "eng": true
      }
    ],
    "events": [
      {
        "date": "2026-06-03",
        "cat": "launch",
        "title": "Olivia Launch",
        "sub": "‘Welcome to the Team’ — photos, press release & piece to camera",
        "marker": "OUT"
      },
      {
        "date": "2026-06-04",
        "cat": "talent",
        "title": "Glen Hoddle",
        "sub": "Guest Talent / OB",
        "marker": "OUT"
      },
      {
        "date": "2026-06-12",
        "cat": "talent",
        "title": "Gary McAllister",
        "sub": "Guest Talent / OB",
        "marker": "OUT"
      },
      {
        "date": "2026-06-25",
        "cat": "talent",
        "title": "Stuart Pearce",
        "sub": "Guest Talent / OB",
        "marker": "OUT"
      },
      {
        "date": "2026-06-08",
        "cat": "buz",
        "title": "The Buz — England v Croatia: Key Battles?",
        "sub": "Piece to camera",
        "marker": "RECORD"
      },
      {
        "date": "2026-06-09",
        "cat": "buz",
        "title": "The Buz — England v Croatia: Key Battles?",
        "sub": "Piece to camera",
        "marker": "OUT"
      },
      {
        "date": "2026-06-15",
        "cat": "buz",
        "title": "The Buz — Scotland/Morocco & Holland/Sweden talking points",
        "sub": "Piece to camera",
        "marker": "RECORD"
      },
      {
        "date": "2026-06-16",
        "cat": "buz",
        "title": "The Buz — Scotland/Morocco & Holland/Sweden talking points",
        "sub": "Piece to camera",
        "marker": "OUT"
      },
      {
        "date": "2026-06-22",
        "cat": "buz",
        "title": "The Buz — Weekly (topic TBC)",
        "sub": "Piece to camera",
        "marker": "RECORD"
      },
      {
        "date": "2026-06-23",
        "cat": "buz",
        "title": "The Buz — Weekly (topic TBC)",
        "sub": "Piece to camera",
        "marker": "OUT"
      },
      {
        "date": "2026-06-29",
        "cat": "buz",
        "title": "The Buz — Weekly (topic TBC)",
        "sub": "Piece to camera",
        "marker": "RECORD"
      },
      {
        "date": "2026-06-30",
        "cat": "buz",
        "title": "The Buz — Weekly (topic TBC)",
        "sub": "Piece to camera",
        "marker": "OUT"
      },
      {
        "date": "2026-07-06",
        "cat": "buz",
        "title": "The Buz — Weekly (topic TBC)",
        "sub": "Piece to camera",
        "marker": "RECORD"
      },
      {
        "date": "2026-07-07",
        "cat": "buz",
        "title": "The Buz — Weekly (topic TBC)",
        "sub": "Piece to camera",
        "marker": "OUT"
      },
      {
        "date": "2026-07-13",
        "cat": "buz",
        "title": "The Buz — Weekly (topic TBC)",
        "sub": "Piece to camera",
        "marker": "RECORD"
      },
      {
        "date": "2026-07-14",
        "cat": "buz",
        "title": "The Buz — Weekly (topic TBC)",
        "sub": "Piece to camera",
        "marker": "OUT"
      },
      {
        "date": "2026-06-17",
        "cat": "fan",
        "title": "Fan Forecast",
        "sub": "Host: Olivia · Dallas",
        "marker": "OUT"
      },
      {
        "date": "2026-06-23",
        "cat": "fan",
        "title": "Fan Forecast",
        "sub": "Host: JCC/Maz/Zac · London (London Bridge)",
        "marker": "OUT"
      },
      {
        "date": "2026-06-24",
        "cat": "fan",
        "title": "Fan Forecast",
        "sub": "Host: JCC/Maz/Zac · London (London Bridge)",
        "marker": "OUT"
      },
      {
        "date": "2026-06-27",
        "cat": "fan",
        "title": "Fan Forecast",
        "sub": "Host: JCC/Maz/Zac · London (London Bridge)",
        "marker": "OUT"
      },
      {
        "date": "2026-07-01",
        "cat": "fan",
        "title": "Fan Forecast",
        "sub": "Host: JCC/Maz/Zac · London",
        "marker": "TBC"
      },
      {
        "date": "2026-07-05",
        "cat": "fan",
        "title": "Fan Forecast",
        "sub": "Host: JCC/Maz/Zac · London",
        "marker": "TBC"
      },
      {
        "date": "2026-07-11",
        "cat": "fan",
        "title": "Fan Forecast",
        "sub": "Host: JCC/Maz/Zac · London",
        "marker": "TBC"
      },
      {
        "date": "2026-07-15",
        "cat": "fan",
        "title": "Fan Forecast",
        "sub": "Host: JCC/Maz/Zac · London",
        "marker": "TBC"
      },
      {
        "date": "2026-07-19",
        "cat": "fan",
        "title": "Fan Forecast",
        "sub": "Host: JCC/Maz/Zac · London",
        "marker": "TBC"
      }
    ]
  }
};
